# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "")
set(CPACK_BINARY_BUNDLE "")
set(CPACK_BINARY_CYGWIN "")
set(CPACK_BINARY_DEB "")
set(CPACK_BINARY_DRAGNDROP "")
set(CPACK_BINARY_FREEBSD "")
set(CPACK_BINARY_IFW "")
set(CPACK_BINARY_NSIS "")
set(CPACK_BINARY_NUGET "")
set(CPACK_BINARY_OSXX11 "")
set(CPACK_BINARY_PACKAGEMAKER "")
set(CPACK_BINARY_PRODUCTBUILD "")
set(CPACK_BINARY_RPM "")
set(CPACK_BINARY_STGZ "")
set(CPACK_BINARY_TBZ2 "")
set(CPACK_BINARY_TGZ "")
set(CPACK_BINARY_TXZ "")
set(CPACK_BINARY_TZ "")
set(CPACK_BINARY_WIX "")
set(CPACK_BINARY_ZIP "")
set(CPACK_BUILD_SOURCE_DIRS "/home/xuwenlong/lycium/main/avro/avro-release-1.11.1/lang/c;/home/xuwenlong/lycium/main/avro/avro-release-1.11.1/armeabi-v7a-build")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/home/xuwenlong/ohos-sdk/linux/native/build-tools/cmake/share/cmake-3.16/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "AvroC built using CMake")
set(CPACK_GENERATOR "TGZ")
set(CPACK_IGNORE_FILES "^/home/xuwenlong/lycium/main/avro/avro-release-1.11.1/armeabi-v7a-build;/\\.gitignore;/\\.svn;\\.swp$;\\.#;/#;.*~")
set(CPACK_INSTALLED_DIRECTORIES "/home/xuwenlong/lycium/main/avro/avro-release-1.11.1/lang/c;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/home/xuwenlong/lycium/usr/avro/armeabi-v7a")
set(CPACK_MODULE_PATH "/home/xuwenlong/lycium/main/avro/avro-release-1.11.1/lang/c")
set(CPACK_NSIS_DISPLAY_NAME "/usr")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "/usr")
set(CPACK_OUTPUT_CONFIG_FILE "/home/xuwenlong/lycium/main/avro/avro-release-1.11.1/armeabi-v7a-build/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "avro-dev@apache.org")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "C bindings for Avro data serialization framework")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/xuwenlong/lycium/main/avro/avro-release-1.11.1/lang/c/README")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "C bindings for Avro data serialization framework")
set(CPACK_PACKAGE_FILE_NAME "avro-c-1.11.1")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "/usr")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "/usr")
set(CPACK_PACKAGE_NAME "avro-c")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Apache Software Foundation")
set(CPACK_PACKAGE_VERSION "1.11.1")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "11")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_RESOURCE_FILE_LICENSE "/home/xuwenlong/lycium/main/avro/avro-release-1.11.1/lang/c/LICENSE")
set(CPACK_RESOURCE_FILE_README "/home/xuwenlong/ohos-sdk/linux/native/build-tools/cmake/share/cmake-3.16/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/home/xuwenlong/ohos-sdk/linux/native/build-tools/cmake/share/cmake-3.16/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "")
set(CPACK_SOURCE_CYGWIN "")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_SOURCE_IGNORE_FILES "^/home/xuwenlong/lycium/main/avro/avro-release-1.11.1/armeabi-v7a-build;/\\.gitignore;/\\.svn;\\.swp$;\\.#;/#;.*~")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/xuwenlong/lycium/main/avro/avro-release-1.11.1/lang/c;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/xuwenlong/lycium/main/avro/avro-release-1.11.1/armeabi-v7a-build/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "avro-c-1.11.1")
set(CPACK_SOURCE_RPM "")
set(CPACK_SOURCE_TBZ2 "")
set(CPACK_SOURCE_TGZ "")
set(CPACK_SOURCE_TOPLEVEL_TAG "OHOS-Source")
set(CPACK_SOURCE_TXZ "")
set(CPACK_SOURCE_TZ "")
set(CPACK_SOURCE_ZIP "")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "OHOS")
set(CPACK_TOPLEVEL_TAG "OHOS-Source")
set(CPACK_WIX_SIZEOF_VOID_P "4")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/xuwenlong/lycium/main/avro/avro-release-1.11.1/armeabi-v7a-build/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
